FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of the code
COPY . .

# Expose the port (adjust if needed)
EXPOSE 8501

# Define the command to run your app
CMD ["streamlit", "run", "streamlit_app.py"]
